// Css
import './globals.css';

// Fonts
import { Montserrat } from 'next/font/google';

const montserrat = Montserrat({
	subsets: ['latin'],
});

// Metadata
export const metadata = {
	title: 'Dmzdev',
	description: 'Generated by create next app',
};

export default function RootLayout({ children }) {
	return (
		<html lang="es-ES">
			<body className={montserrat.className}>{children}</body>
		</html>
	);
}
